id: I01E813B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:56:04+00:00'
last_modified: '2022-06-08T01:33:54.176969+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29280
  title: ལག་ལེན་ལམ་སྟོན་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    EB84:
      image_group_id: I1KG18466
      title: ''
      total_pages: 196
      order: 1
      base_file: EB84.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
