id: P004506
initial_creation_type: ocr
source_metadata:
  id: bdr:W29280
  title: ལག་ལེན་ལམ་སྟོན་སྣང་བ།
  author: ''
  volumes:
    e1d28109a4714d8582107ba8054be3ef:
      image_group_id: I1KG18466
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
